document.writeln("<div class=\"footer\">");
document.writeln("    <div class=\"mainfooter\">");
document.writeln("        <div class=\"contactbtn\">");
document.writeln("            <a href=\"mailto:ilcsitramp@gmail.com\">CONTACT</a>");
document.writeln("        </div>");
document.writeln("        <div class=\"foot_contact\">");
document.writeln("            <ul>");
document.writeln("                <li>");
document.writeln("                    <a href=\"\" alt=\"facebook\">");
document.writeln("                        <i class=\"fab fa-facebook-square\"></i>");
document.writeln("                    </a>");
document.writeln("                    </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\"\" alt=\"linkedin\">");
document.writeln("                        <i class=\"fab fa-linkedin\"></i>");
document.writeln("                    </a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\"\" alt=\"behance\">");
document.writeln("                        <i class=\"fab fa-behance-square\"></i>");
document.writeln("                    </a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\"\" alt=\"instagram\">");
document.writeln("                        <i class=\"fab fa-instagram-square\"></i>");
document.writeln("                    </a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("            <a href=\"mailto:ilcsitramp@gmail.com\">ilcsitramp@gmail.com</a>");
document.writeln("            <a href=\"tel:+886-928291993\">0928-291993</a>");
document.writeln("        </div>");
document.writeln("        <div class=\"foocopyright\">Copyright© Ilcsi Shen All rights Reserved.</div>");
document.writeln("    </div>");
document.writeln("</div>");